# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/bionic64"
  config.vm.box = "gutehall/ubuntu24-04"
  config.vm.box_version = "2024.08.30"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_roles_path = "./roles"
    ansible.verbose = true # eq "-v" ansible.verbose = "-vvv"
  end
end
